### ISSUE TITLE
TypeError: Logger.__init__() got an unexpected keyword argument 'patcher'

### ISSUE THREAD

**Issue by borisprosto** [GrowthEngineAI/async-openai#5]
After installing the async-openai package I try to run the example from the documentation and get an error:
File "D:\PythonProject\async-openai-bot\venv\lib\site-packages\fileio\utils\logs.py", line 73, in <module>
    logger = Logger(
TypeError: Logger.__init__() got an unexpected keyword argument 'patcher'

If you change the patcher to patchers (82 line logs.py), everything works.

**Comment by trisongz** [comment]
Thanks for pointing this out - this was a bug that happened when `loguru` changed the init params in later versions. The underlying libraries have now all been patched to ensure this works.
