### ISSUE TITLE
suppress output

### ISSUE THREAD

**Issue by aevela** [GrowthEngineAI/async-openai#9]
When using OpenAI.chat.async_create() to call the OpenAI api there is always an output, even when debug_enabled = False.

The output looks something like:
INFO     2023-07-21 01:22:57.691: httpx._client:_send_single_request: HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Is there any way to suppress this output?

**Comment by trisongz** [comment]
Hi - the recent updates to `httpx` caused logging to be verbose by default. The latest version (`v0.0.33`) now resolves that which will disable the `httpx` logger whenever `debug_enabled` = False.
